apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
  namespace: services
spec:
  destination:
    namespace: demo
    server: "https://kubernetes.default.svc"
  source:
    path: helm/helm-nginx
    repoURL: "https://github.com/1Psy/argocd-vault-example.git"
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: CHART_VALUES
          value: values.demo.yaml            
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

