apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-nginx.fullname" . }}
  labels:
    {{- include "helm-nginx.labels" . | nindent 4 }}
data:
{{- with .Values.configmap }}
{{ toYaml . | indent 2 }}
{{- end }}