kind: Secret
apiVersion: v1
metadata:
  name: {{ include "helm-nginx.fullname" . }}
  labels:
    {{- include "helm-nginx.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- with .Values.secrets }}
{{ toYaml . | indent 2 }}
{{- end }}