apiVersion: v1
kind: Namespace
metadata:
  name: test
---
kind: Secret
apiVersion: v1
metadata:
  name: test-secret-yaml
  namespace: test
type: Opaque
stringData:
  SECRET_KEY: <path:dev/data/nginx#SECRET_KEY>